name: Terraform Lint

on:
  pull_request:
    branches:
      - main  

jobs:
  terraform-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.10.5'

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Initialize TFLint
        run: tflint --init

      - name: Initialize Terraform
        run: terraform init  

      - name: Run `terraform fmt` (check formatting)
        run: terraform fmt --recursive -check

      - name: Run `terraform validate` (check syntax)
        run: terraform validate 

      - name: Run TFLint
        run: |
          tflint --recursive --config "$(pwd)/.tflint.hcl"